tap "derailed/k9s"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "archey"
brew "autojump"
brew "ffmpeg"
brew "go"
brew "jq"
brew "jsonnet"
brew "k9s"
brew "kubernetes-cli", link: false
brew "ncdu"
brew "youtube-dl"
brew "zsh"
cask "keepassxc"
